name: Update library aaa every minute

# This ensures that only a single workflow of this type will run at a time
concurrency: update-library-aaa

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug env vars
        shell: bash
        run: |
          echo -e "GITHUB_REPOSITORY: $GITHUB_REPOSITORY\n"
          echo -e "GITHUB_WORKSPACE: $GITHUB_WORKSPACE\n"
          echo -e "GITHUB_SHA: $GITHUB_SHA\n"
          echo -e "GITHUB_REF: $GITHUB_REF\n"
          echo -e "GITHUB_HEAD_REF: $GITHUB_HEAD_REF\n"
          echo -e "GITHUB_BASE_REF: $GITHUB_BASE_REF\n"
          echo -e "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME\n"
          echo -e "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH\n"
          echo -e "GITHUB_RUN_ID: $GITHUB_RUN_ID\n"
          echo -e "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER\n"

      - uses: actions/checkout@v2
        with:  
          submodules: 'true'

      - name: Update submodule libraries/aaa
        id: update-library
        run: |
          git submodule status libraries/aaa
          echo "::set-output name=previous_ref::$(git submodule status | awk '{print $1}' | sed 's/-//' | sed 's/+//' | sed 's/U//')"
          git submodule update --remote libraries/aaa
          echo "::set-output name=current_ref::$(git submodule status | awk '{print $1}' | sed 's/-//' | sed 's/+//' | sed 's/U//')"

      - name: Commit submodule update
        if: ${{ steps.update-library.outputs.previous_ref != steps.update-library.outputs.current_ref }}
        run: |
          git add libraries/aaa && git commit -m "update library aaa to ${{ steps.update-library.outputs.current_ref }}"

      - name: Create Pull Request with library update
        if: ${{ steps.update-library.outputs.previous_ref != steps.update-library.outputs.current_ref }}
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            libraries/**
          title: "Update library aaa to ${{ steps.update-library.outputs.current_ref }}"
          body: |
            Update submodule libraries/aaa
            - Previous ref: ${{ steps.update-library.outputs.previous_ref }}
            - Current ref: ${{ steps.update-library.outputs.current_ref }}
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
